import type {
  Trilha,
  Badge,
  Missao,
  RankingEntry,
  PostComunidade,
  Beneficio,
  Liga,
  Notificacao,
  Level,
  QuizPergunta,
} from "./types";

export const niveis: Level[] = [
  { id: 1, name: "Iniciante", minXp: 0, icon: "Sprout" },
  { id: 2, name: "Aprendiz", minXp: 300, icon: "BookOpen" },
  { id: 3, name: "Conhecedor", minXp: 800, icon: "Sparkles" },
  { id: 4, name: "Especialista", minXp: 1500, icon: "Target" },
  { id: 5, name: "Conselheiro", minXp: 2800, icon: "Crown" },
  { id: 6, name: "Embaixador", minXp: 5000, icon: "Landmark" },
];

export const ligas: Liga[] = [
  { id: "l1", nome: "Bronze", cor: "#CD7F32", minXp: 0, descricao: "Todo especialista começa aqui. A base da jornada." },
  { id: "l2", nome: "Prata", cor: "#C0C0C0", minXp: 500, descricao: "Você está ganhando ritmo e conhecimento." },
  { id: "l3", nome: "Ouro", cor: "#FFD700", minXp: 1200, descricao: "Vendedores de destaque com sólido domínio da marca." },
  { id: "l4", nome: "Safira", cor: "#0F52BA", minXp: 2000, descricao: "Especialistas reconhecidos com performance acima da média." },
  { id: "l5", nome: "Rubi", cor: "#E0115F", minXp: 3500, descricao: "Elite dos vendedores Fassi. Referência em sua loja." },
  { id: "l6", nome: "Esmeralda", cor: "#50C878", minXp: 5500, descricao: "Top performers nacionais. Próximos do título de Embaixador." },
  { id: "l7", nome: "Diamante", cor: "#B9F2FF", minXp: 8000, descricao: "A liga mais exclusiva. Apenas os melhores dos melhores." },
];

export const trilhas: Trilha[] = [
  {
    id: "historia",
    titulo: "História da Marca",
    descricao: "A jornada da Marken Fassi: da origem ao luxo brasileiro",
    cor: "#C9B37C",
    icone: "BookOpen",
    xpTotal: 400,
    aulas: [
      {
        id: "h1",
        trilhaId: "historia",
        titulo: "As raízes da Fassi",
        duracao: "4 min",
        tipo: "video",
        conteudo: "Conheça a história de como a Marken Fassi nasceu de uma visão de levar o luxo europeu ao mercado brasileiro com identidade própria.",
        xp: 50,
      },
      {
        id: "h2",
        trilhaId: "historia",
        titulo: "O que nos torna premium",
        duracao: "6 min",
        tipo: "video",
        conteudo: "Os pilares que sustentam a marca: qualidade dos fios, acabamento artesanal, design atemporal e experiência de uso.",
        xp: 50,
      },
      {
        id: "h3",
        trilhaId: "historia",
        titulo: "Quiz: História Fassi",
        duracao: "3 min",
        tipo: "quiz",
        conteudo: "Teste seu conhecimento sobre a história da marca.",
        xp: 100,
      },
    ],
  },
  {
    id: "tecidos",
    titulo: "Universo dos Tecidos",
    descricao: "Algodão egípcio, percal, linho: domine cada fio",
    cor: "#7A8B6F",
    icone: "Layers",
    xpTotal: 600,
    aulas: [
      {
        id: "t1",
        trilhaId: "tecidos",
        titulo: "Algodão Egípcio: o rei dos fios",
        duracao: "8 min",
        tipo: "video",
        conteudo: "O algodão egípcio é considerado o melhor do mundo por seus fios extra-longos. Entenda por que isso importa na hora de vender.",
        xp: 80,
      },
      {
        id: "t2",
        trilhaId: "tecidos",
        titulo: "Percal vs. Fio a Fio",
        duracao: "6 min",
        tipo: "video",
        conteudo: "A diferença entre percal e fio a fio vai muito além do toque. Aprenda a traduzir isso em argumentos de venda.",
        xp: 80,
      },
      {
        id: "t3",
        trilhaId: "tecidos",
        titulo: "Linho: o luxo natural",
        duracao: "5 min",
        tipo: "texto",
        conteudo: "O linho é o tecido mais antigo do mundo. Conheça suas características únicas e como posicionar para o cliente premium.",
        xp: 60,
      },
      {
        id: "t4",
        trilhaId: "tecidos",
        titulo: "Quiz: Tecidos e Fios",
        duracao: "4 min",
        tipo: "quiz",
        conteudo: "Mostre que você entende de fios.",
        xp: 120,
      },
    ],
  },
  {
    id: "vender-luxo",
    titulo: "Como Vender Luxo",
    descricao: "A arte de transformar interesse em desejo",
    cor: "#A47864",
    icone: "Crown",
    xpTotal: 800,
    aulas: [
      {
        id: "v1",
        trilhaId: "vender-luxo",
        titulo: "A psicologia do cliente premium",
        duracao: "10 min",
        tipo: "video",
        conteudo: "O cliente de luxo não compra produto — compra significado. Aprenda a ler o que ele realmente quer.",
        xp: 100,
      },
      {
        id: "v2",
        trilhaId: "vender-luxo",
        titulo: "Storytelling de venda",
        duracao: "7 min",
        tipo: "video",
        conteudo: "Cada coleção Fassi tem uma história. Use isso para criar conexão emocional no momento da venda.",
        xp: 100,
      },
      {
        id: "v3",
        trilhaId: "vender-luxo",
        titulo: "Atendimento premium: o padrão Ritz-Carlton",
        duracao: "8 min",
        tipo: "video",
        conteudo: "Os 3 passos do atendimento que faz o cliente sentir que entrou em um mundo à parte.",
        xp: 100,
      },
      {
        id: "v4",
        trilhaId: "vender-luxo",
        titulo: "Técnicas de fechamento",
        duracao: "6 min",
        tipo: "video",
        conteudo: "Como fechar a venda sem pressão, com elegância e confiança.",
        xp: 80,
      },
      {
        id: "v5",
        trilhaId: "vender-luxo",
        titulo: "Quiz: Venda Premium",
        duracao: "5 min",
        tipo: "quiz",
        conteudo: "Você está pronto para vender luxo?",
        xp: 150,
      },
    ],
  },
  {
    id: "visual-merch",
    titulo: "Visual Merchandising",
    descricao: "A arte de arrumar cama, mesa e banho",
    cor: "#1F5C63",
    icone: "BedDouble",
    xpTotal: 500,
    aulas: [
      {
        id: "vm1",
        trilhaId: "visual-merch",
        titulo: "Arrumação de cama: o impacto visual",
        duracao: "9 min",
        tipo: "video",
        conteudo: "A cama arrumada é o cartão de visitas da loja. Aprenda a técnica Fassi de camadas.",
        xp: 100,
      },
      {
        id: "vm2",
        trilhaId: "visual-merch",
        titulo: "Mesa posta: elegância à brasileira",
        duracao: "7 min",
        tipo: "video",
        conteudo: "Como montar uma mesa posta que conta uma história e faz o cliente querer levar tudo.",
        xp: 100,
      },
      {
        id: "vm3",
        trilhaId: "visual-merch",
        titulo: "Vitrine que para o cliente",
        duracao: "6 min",
        tipo: "video",
        conteudo: "Os princípios de uma vitrine que faz o cliente entrar na loja.",
        xp: 80,
      },
      {
        id: "vm4",
        trilhaId: "visual-merch",
        titulo: "Quiz: Visual Merchandising",
        duracao: "4 min",
        tipo: "quiz",
        conteudo: "Teste seu olhar para merchandising.",
        xp: 120,
      },
    ],
  },
  {
    id: "neurovendas",
    titulo: "Neurovendas",
    descricao: "O cérebro do cliente e o processo de decisão",
    cor: "#8B5CF6",
    icone: "Brain",
    xpTotal: 700,
    aulas: [
      {
        id: "n1",
        trilhaId: "neurovendas",
        titulo: "Como o cérebro decide comprar",
        duracao: "10 min",
        tipo: "video",
        conteudo: "Entenda os gatilhos mentais que ativam a decisão de compra no cliente premium.",
        xp: 120,
      },
      {
        id: "n2",
        trilhaId: "neurovendas",
        titulo: "Ancoragem de preço",
        duracao: "6 min",
        tipo: "video",
        conteudo: "Como apresentar preço sem gerar resistência usando ancoragem.",
        xp: 100,
      },
      {
        id: "n3",
        trilhaId: "neurovendas",
        titulo: "Objeções: o mapa do tesouro",
        duracao: "8 min",
        tipo: "video",
        conteudo: "Cada objeção é uma oportunidade. Aprenda a transformar 'está caro' em 'é um investimento'.",
        xp: 120,
      },
      {
        id: "n4",
        trilhaId: "neurovendas",
        titulo: "Quiz: Neurovendas",
        duracao: "5 min",
        tipo: "quiz",
        conteudo: "Você domina a mente do cliente?",
        xp: 150,
      },
    ],
  },
  {
    id: "colecoes",
    titulo: "Coleções Fassi",
    descricao: "Cada coleção, uma história para contar",
    cor: "#EC4899",
    icone: "Sparkles",
    xpTotal: 550,
    aulas: [
      {
        id: "c1",
        trilhaId: "colecoes",
        titulo: "Coleção Inverno 2026",
        duracao: "8 min",
        tipo: "video",
        conteudo: "Conheça os lançamentos, paletas e argumentos de venda da nova coleção.",
        xp: 100,
      },
      {
        id: "c2",
        trilhaId: "colecoes",
        titulo: "Coleção CasaCor",
        duracao: "6 min",
        tipo: "video",
        conteudo: "A coleção exclusiva desenvolvida para a CasaCor e como usá-la como argumento.",
        xp: 100,
      },
      {
        id: "c3",
        trilhaId: "colecoes",
        titulo: "Linha Banho: o ritual",
        duracao: "5 min",
        tipo: "video",
        conteudo: "A linha de banho como ritual de autocuidado — não apenas toalhas.",
        xp: 80,
      },
      {
        id: "c4",
        trilhaId: "colecoes",
        titulo: "Quiz: Coleções",
        duracao: "4 min",
        tipo: "quiz",
        conteudo: "Você conhece cada coleção?",
        xp: 120,
      },
    ],
  },
];

export const quizzes: Record<string, QuizPergunta[]> = {
  h3: [
    {
      id: "h3q1",
      pergunta: "Qual é o principal diferencial do algodão egípcio usado pela Fassi?",
      opcoes: ["É mais barato", "Tem fios extra-longos", "Vem apenas do Egito", "É mais colorido"],
      correta: 1,
      explicacao: "Os fios extra-longos do algodão egípcio criam um tecido mais suave, durável e resistente a pilling.",
    },
    {
      id: "h3q2",
      pergunta: "A Marken Fassi se posiciona como uma marca de:",
      opcoes: ["Luxo acessível", "Premium brasileira", "Importada", "Econômica"],
      correta: 1,
      explicacao: "A Fassi é uma marca premium brasileira que combina qualidade internacional com identidade nacional.",
    },
    {
      id: "h3q3",
      pergunta: "O manifesto Fassi fala sobre entregar:",
      opcoes: ["Apenas produtos", "Conforto, beleza, memória e futuro", "O menor preço", "Exclusividade total"],
      correta: 1,
      explicacao: "Vender enxoval Fassi é entregar conforto, beleza, memória e futuro para a família do cliente.",
    },
  ],
  t4: [
    {
      id: "t4q1",
      pergunta: "Qual tecido é conhecido pelos fios extra-longos?",
      opcoes: ["Percal", "Linho", "Algodão egípcio", "Poliéster"],
      correta: 2,
      explicacao: "O algodão egípcio possui fios extra-longos que geram um tecido superior em suavidade e durabilidade.",
    },
    {
      id: "t4q2",
      pergunta: "A principal diferença entre percal e fio a fio está em:",
      opcoes: ["O preço", "A forma de tecelagem e toque", "A cor", "O tamanho"],
      correta: 1,
      explicacao: "O percal é um plano de tecelagem mais fechado e fosco, enquanto o fio a fio tem toque mais sedoso.",
    },
    {
      id: "t4q3",
      pergunta: "O linho é valorizado por ser:",
      opcoes: ["O tecido sintético mais leve", "O tecido natural mais antigo e respirável", "O mais barato", "O mais colorido"],
      correta: 1,
      explicacao: "O linho é o tecido natural mais antigo do mundo, valorizado por sua respirabilidade e charme natural.",
    },
  ],
  v5: [
    {
      id: "v5q1",
      pergunta: "O cliente premium compra principalmente:",
      opcoes: ["Preço baixo", "Significado e experiência", "Quantidade", "Promoções"],
      correta: 1,
      explicacao: "O cliente de luxo busca significado, experiência e pertencimento — não preço.",
    },
    {
      id: "v5q2",
      pergunta: "O storytelling de venda funciona porque:",
      opcoes: ["É mais rápido", "Cria conexão emocional", "É mais barato", "Substitui o produto"],
      correta: 1,
      explicacao: "Histórias ativam áreas emocionais do cérebro, criando conexão que transcende o produto.",
    },
    {
      id: "v5q3",
      pergunta: "No atendimento premium, o ideal é:",
      opcoes: ["Pressionar para fechar rápido", "Acolher, entender e guiar", "Falar o mínimo possível", "Mostrar todos os produtos"],
      correta: 1,
      explicacao: "O atendimento premium acolhe, entende a necessidade e guia o cliente com elegância.",
    },
    {
      id: "v5q4",
      pergunta: "Ao lidar com a objeção 'está caro', você deve:",
      opcoes: ["Concordar e descontar", "Explicar o valor e o investimento", "Ignorar", "Mudar de assunto"],
      correta: 1,
      explicacao: "Transforme 'caro' em 'investimento' mostrando o valor: durabilidade, qualidade e experiência.",
    },
  ],
  vm4: [
    {
      id: "vm4q1",
      pergunta: "A cama arrumada na loja serve como:",
      opcoes: ["Apenas decoração", "Cartão de visitas da loja", "Estoque", "Desperdício de espaço"],
      correta: 1,
      explicacao: "A cama arrumada é o cartão de visitas — é o que faz o cliente parar e querer tocar.",
    },
    {
      id: "vm4q2",
      pergunta: "A técnica de camadas na arrumação Fassi significa:",
      opcoes: ["Empilhar tudo", "Criar profundidade visual com sobreposições", "Usar apenas uma cor", "Deixar minimalista"],
      correta: 1,
      explicacao: "As camadas criam profundidade e convidam o cliente a imaginar aquela cama em sua casa.",
    },
  ],
  n4: [
    {
      id: "n4q1",
      pergunta: "O gatilho de ancoragem de preço funciona porque:",
      opcoes: ["É uma mentira", "O cérebro usa a primeira referência como base", "É ilegal", "Só funciona com ricos"],
      correta: 1,
      explicacao: "O cérebro ancora no primeiro número visto. Apresentar o item mais caro primeiro faz os outros parecerem acessíveis.",
    },
    {
      id: "n4q2",
      pergunta: "Uma objeção é melhor entendida como:",
      opcoes: ["Um não definitivo", "Um pedido de mais informação", "Falta de educação", "Sinal de que deve desistir"],
      correta: 1,
      explicacao: "Cada objeção é um pedido de mais informação — é o cliente dizendo 'me convença melhor'.",
    },
    {
      id: "n4q3",
      pergunta: "A neurovendas estuda:",
      opcoes: ["Como enganar o cliente", "Como o cérebro decide comprar", "Apenas marketing digital", "Estatística de vendas"],
      correta: 1,
      explicacao: "Neurovendas aplica neurociência ao processo de vendas, entendendo como decisões são tomadas no cérebro.",
    },
  ],
  c4: [
    {
      id: "c4q1",
      pergunta: "A Coleção CasaCor é especial porque:",
      opcoes: ["É mais barata", "É exclusiva e desenvolvida para o evento", "Tem mais cores", "É importada"],
      correta: 1,
      explicacao: "A coleção CasaCor é exclusiva, criada para o maior evento de arquitetura e design da América Latina.",
    },
    {
      id: "c4q2",
      pergunta: "A linha de banho Fassi deve ser apresentada como:",
      opcoes: ["Apenas toalhas", "Um ritual de autocuidado", "Produto de limpeza", "Item de reposição"],
      correta: 1,
      explicacao: "A linha de banho é um ritual de autocuidado — o vendedor que entende isso vende muito mais.",
    },
  ],
};

export const badges: Badge[] = [
  { id: "b1", nome: "Bem-vindo à Casa", descricao: "Completou o onboarding", icone: "Home", cor: "#C9B37C", conquistado: true, data: "2026-07-15" },
  { id: "b2", nome: "Primeira Aula", descricao: "Concluiu sua primeira aula", icone: "PlayCircle", cor: "#7A8B6F", conquistado: true, data: "2026-07-15" },
  { id: "b3", nome: "Streak de 7 dias", descricao: "Acessou 7 dias seguidos", icone: "Flame", cor: "#A47864", conquistado: true, data: "2026-07-21" },
  { id: "b4", nome: "Quiz Perfeito", descricao: "Acertou todas no primeiro quiz", icone: "CheckCircle", cor: "#1F5C63", conquistado: false },
  { id: "b5", nome: "Primeira Vitrine", descricao: "Postou sua primeira vitrine", icone: "Camera", cor: "#EC4899", conquistado: false },
  { id: "b6", nome: "Especialista em Tecidos", descricao: "Completou a trilha de Tecidos", icone: "Layers", cor: "#7A8B6F", conquistado: false },
  { id: "b7", nome: "Vendedor Premium", descricao: "Completou a trilha de Vender Luxo", icone: "Crown", cor: "#A47864", conquistado: false },
  { id: "b8", nome: "Streak de 30 dias", descricao: "Acessou 30 dias seguidos", icone: "Flame", cor: "#E0115F", conquistado: false },
  { id: "b9", nome: "Top 10 Nacional", descricao: "Entrou no Top 10 do ranking", icone: "Trophy", cor: "#FFD700", conquistado: false },
  { id: "b10", nome: "Embaixador", descricao: "Alcançou o nível Embaixador", icone: "Star", cor: "#C9B37C", conquistado: false },
  { id: "b11", nome: "Mentor", descricao: "Ajudou 10 vendedores na comunidade", icone: "Heart", cor: "#EC4899", conquistado: false },
  { id: "b12", nome: "Colecionador", descricao: "Resgatou 5 benefícios do clube", icone: "Gift", cor: "#8B5CF6", conquistado: false },
];

export const missoes: Missao[] = [
  { id: "m1", titulo: "Aula diária", descricao: "Complete 1 aula hoje", xp: 50, moedas: 10, progresso: 0, total: 1, tipo: "semanal", prazo: "Hoje" },
  { id: "m2", titulo: "Semana dourada", descricao: "Complete 5 aulas esta semana", xp: 200, moedas: 50, progresso: 2, total: 5, tipo: "semanal", prazo: "5 dias" },
  { id: "m3", titulo: "Quiz master", descricao: "Acerte 10 perguntas de quiz", xp: 150, moedas: 30, progresso: 4, total: 10, tipo: "semanal", prazo: "5 dias" },
  { id: "m4", titulo: "Vitrine da semana", descricao: "Poste 3 fotos de vitrine", xp: 100, moedas: 25, progresso: 1, total: 3, tipo: "semanal", prazo: "5 dias" },
  { id: "m5", titulo: "Mestre das Trilhas", descricao: "Complete 3 trilhas este mês", xp: 500, moedas: 100, progresso: 1, total: 3, tipo: "mensal", prazo: "18 dias" },
  { id: "m6", titulo: "Embaixador ativo", descricao: "Acesse a plataforma 20 dias no mês", xp: 300, moedas: 80, progresso: 7, total: 20, tipo: "mensal", prazo: "18 dias" },
];

export const rankingNacional: RankingEntry[] = [
  { id: "r1", nome: "Ana Beatriz", loja: "Casa & Estilo", estado: "SP", avatar: "AB", xp: 8450, nivel: 6, streak: 42, posicao: 1 },
  { id: "r2", nome: "Rodrigo Mendes", loja: "Enxoval Real", estado: "RJ", avatar: "RM", xp: 7800, nivel: 6, streak: 35, posicao: 2 },
  { id: "r3", nome: "Carla Souza", loja: "Lar Premium", estado: "MG", avatar: "CS", xp: 6900, nivel: 5, streak: 28, posicao: 3 },
  { id: "r4", nome: "Felipe Andrade", loja: "Casa Marken Fassi BH", estado: "MG", avatar: "FA", xp: 5200, nivel: 5, streak: 14, posicao: 4 },
  { id: "r5", nome: "Juliana Lima", loja: "Têxtil Elegância", estado: "RS", avatar: "JL", xp: 4800, nivel: 4, streak: 21, posicao: 5 },
  { id: "r6", nome: "Marina Costa", loja: "Casa & Estilo", estado: "SP", avatar: "MC", xp: 4200, nivel: 4, streak: 7, posicao: 6 },
  { id: "r7", nome: "Você", loja: "Casa Marken Fassi SP", estado: "SP", avatar: "EU", xp: 3850, nivel: 4, streak: 7, posicao: 7, souEu: true },
  { id: "r8", nome: "Bruno Oliveira", loja: "Enxoval Real", estado: "RJ", avatar: "BO", xp: 3600, nivel: 4, streak: 12, posicao: 8 },
  { id: "r9", nome: "Patricia Alves", loja: "Lar Premium", estado: "BA", avatar: "PA", xp: 3200, nivel: 3, streak: 5, posicao: 9 },
  { id: "r10", nome: "Gustavo Ferreira", loja: "Têxtil Elegância", estado: "RS", avatar: "GF", xp: 2900, nivel: 3, streak: 9, posicao: 10 },
];

export const postsComunidade: PostComunidade[] = [
  {
    id: "p1",
    autor: "Ana Beatriz",
    avatar: "AB",
    loja: "Casa & Estilo — SP",
    tempo: "2h",
    texto: "Montei a vitrine com a nova coleção e o resultado ficou deslumbrante! Os clientes não conseguem passar sem parar e elogiar o cuidado em cada detalhe.",
    curtidas: 47,
    comentarios: 12,
    tipo: "vitrine",
  },
  {
    id: "p2",
    autor: "Rodrigo Mendes",
    avatar: "RM",
    loja: "Enxoval Real — RJ",
    tempo: "5h",
    texto: "Dica de ouro: quando o cliente fala que está caro, eu pergunto: 'Há quanto tempo você troca seu enxoval?' A resposta sempre abre a conversa para qualidade e durabilidade. Funciona demais!",
    curtidas: 89,
    comentarios: 23,
    tipo: "dica",
  },
  {
    id: "p3",
    autor: "Carla Souza",
    avatar: "CS",
    loja: "Lar Premium — MG",
    tempo: "8h",
    texto: "Alguém já apresentou a linha de banho como 'ritual de autocuidado'? Testei essa abordagem ontem e a cliente levou o conjunto completo. A formação sobre atendimento da Universidade fez toda a diferença.",
    curtidas: 65,
    comentarios: 18,
    tipo: "venda",
  },
  {
    id: "p4",
    autor: "Juliana Lima",
    avatar: "JL",
    loja: "Têxtil Elegância — RS",
    tempo: "1d",
    texto: "Dúvida: qual a melhor forma de apresentar o percal vs fio a fio para um cliente que não entende nada de tecidos? Quais argumentos vocês usam?",
    curtidas: 34,
    comentarios: 27,
    tipo: "duvida",
  },
  {
    id: "p5",
    autor: "Felipe Andrade",
    avatar: "FA",
    loja: "Casa Marken Fassi BH — MG",
    tempo: "2d",
    texto: "A Casa Marken Fassi virou parte da minha rotina diária. Aprendo algo novo todo dia e isso reflete no cuidado com cada cliente. Gratidão, marca!",
    curtidas: 112,
    comentarios: 15,
    tipo: "dica",
  },
];

export const beneficios: Beneficio[] = [
  { id: "bf1", nome: "Jogo de cama Fassi", descricao: "Jogo de cama king 4 peças — linha premium", custoMoedas: 500, categoria: "produto", icone: "BedDouble" },
  { id: "bf2", nome: "Conjunto de banho", descricao: "Conjunto toalhas + roupão — linha premium", custoMoedas: 350, categoria: "produto", icone: "ShowerHead" },
  { id: "bf3", nome: "Visita à fábrica Fassi", descricao: "Visita guiada à fábrica em SP + almoço com a equipe", custoMoedas: 1200, categoria: "experiencia", icone: "Factory", destaque: true },
  { id: "bf4", nome: "CasaCor 2026", descricao: "Ingresso + credencial VIP para a CasaCor", custoMoedas: 800, categoria: "evento", icone: "Ticket", destaque: true },
  { id: "bf5", nome: "Mentoria 1:1", descricao: "Sessão de mentoria com executivo da Fassi", custoMoedas: 600, categoria: "experiencia", icone: "Users" },
  { id: "bf6", nome: "Certificado Especialista", descricao: "Certificado impresso + digital de especialista Fassi", custoMoedas: 300, categoria: "certificado", icone: "Award" },
  { id: "bf7", nome: "Kit brindes Fassi", descricao: "Ecobag + caderno + caneta premium da marca", custoMoedas: 150, categoria: "produto", icone: "Gift" },
  { id: "bf8", nome: "Final de semana em SP", descricao: "Viagem: passagem + hospedagem 2 noites em SP", custoMoedas: 2000, categoria: "viagem", icone: "Plane", destaque: true },
  { id: "bf9", nome: "Encontro Embaixadores", descricao: "Evento exclusivo anual para top vendedores", custoMoedas: 1500, categoria: "evento", icone: "Sparkles", destaque: true },
  { id: "bf10", nome: "Certificado Embaixador", descricao: "Certificação máxima — reconhecimento nacional", custoMoedas: 1000, categoria: "certificado", icone: "Crown" },
  { id: "bf11", nome: "Travesseiro Premium", descricao: "Travesseiro tecnológico com fronha da linha Fassi", custoMoedas: 250, categoria: "produto", icone: "BedDouble" },
  { id: "bf12", nome: "Workshop de Vendas", descricao: "Treinamento presencial com especialistas de mercado", custoMoedas: 450, categoria: "experiencia", icone: "Sparkles" },
  { id: "bf13", nome: "Diária em hotel parceiro", descricao: "1 diária em hotel parceiro selecionado", custoMoedas: 900, categoria: "viagem", icone: "Plane" },
  { id: "bf14", nome: "City tour cultural SP", descricao: "Passeio guiado pelos pontos culturais de São Paulo", custoMoedas: 700, categoria: "viagem", icone: "Plane" },
  { id: "bf15", nome: "Live exclusiva de lançamento", descricao: "Acesso antecipado às novas coleções em live privada", custoMoedas: 200, categoria: "evento", icone: "Ticket" },
  { id: "bf16", nome: "Jantar com a diretoria", descricao: "Jantar de networking com a liderança da Marken Fassi", custoMoedas: 1300, categoria: "evento", icone: "Users" },
];

export const notificacoesIniciais: Notificacao[] = [
  { id: "n1", tipo: "streak", titulo: "Streak ativa!", texto: "Voce esta com 7 dias de streak. Nao pare agora!", tempo: "agora", lida: false },
  { id: "n2", tipo: "missao", titulo: "Missão quase lá!", texto: "Complete mais 3 aulas para concluir a Semana Dourada (+200 XP)", tempo: "1h", lida: false },
  { id: "n3", tipo: "comunidade", titulo: "Rodrigo curtiu seu post", texto: "Sua dica de vendas fez sucesso na comunidade!", tempo: "3h", lida: false },
  { id: "n4", tipo: "badge", titulo: "Nova badge disponível!", texto: "Complete a trilha de Tecidos para ganhar a badge Especialista", tempo: "1d", lida: true },
  { id: "n5", tipo: "sistema", titulo: "Nova coleção disponível", texto: "A trilha Coleção Inverno 2026 foi liberada na Academia", tempo: "2d", lida: true },
];

export const iaSugestoes = [
  "Qual a diferença entre percal e fio a fio?",
  "Como responder quando o cliente diz que está caro?",
  "Monte um argumento de venda para a coleção Inverno 2026",
  "Qual tecido recomendar para um cliente com pele sensível?",
  "Como montar uma mesa posta que impressione?",
  "Compare as coleções CasaCor e Inverno 2026",
];

export const iaRespostas: Record<string, string> = {
  "percal": "**Percal vs. Fio a Fio**\n\nA diferença está na **tecelagem** e no **toque**:\n\n• **Percal**: tecelagem plana, mais fechada e fosca. Toque seco e crocante. Transmite sensação de frescor e durabilidade. Ideal para quem gosta de um toque mais estruturado.\n\n• **Fio a fio** (ou jacquard): tecelagem com textura, toque mais sedoso e fluido. Tem brilho natural e sensação de luxo. Ideal para clientes que buscam sofisticação tátil.\n\n**Argumento de venda**: \"O percal é como um linho impecável — fresco e durável. O fio a fio é como seda — envolvente e luxuoso. Ambos são algodão egípcio de altíssima qualidade. A escolha depende do que seu cliente prefere sentir ao toque.\"",
  "caro": "**Respondendo à objeção 'está caro'**\n\nTransforme 'caro' em 'investimento' com estes passos:\n\n1. **Valide**: \"Entendo perfeitamente. É um valor importante.\"\n2. **Ancore**: \"Um enxoval Fassi dura 10+ anos com qualidade. Dividindo pelo tempo de uso, custa menos que R$ 1/dia.\"\n3. **Compare**: \"Um jogo de cama comum precisa ser trocado a cada 2 anos. O nosso mantém cor, toque e forma por muito mais tempo.\"\n4. **Conecte**: \"Você não está comprando tecido — está comprando 10 anos de noites bem dormidas.\"\n\n**Dica extra**: nunca discuta preço. Discuta **valor**.",
  "inverno": "**Argumento de venda — Coleção Inverno 2026**\n\nA coleção Inverno 2026 traz **tons terrosos aquecidos** (terracota, mostarda, verde-musgo) com **texturas sobrepostas**:\n\n• **Storytelling**: \"Esta coleção foi inspirada nas tardes de inverno brasileiras — aquela luz dourada que entra pela janela e convida para uma soneca.\"\n• **Argumento sensorial**: \"Sinta a textura — é como um abraço. As camadas de percal e fio a fio criam profundidade que você só encontra na Fassi.\"\n• **Exclusividade**: \"É uma edição limitada. Quando o inverno passar, esses tons não voltam.\"\n• **Fechamento**: \"Posso reservar o conjunto king para você? Garanto que vai transformar seu quarto neste inverno.\"",
  "pele": "**Recomendação para pele sensível**\n\nPara clientes com pele sensível, recomende:\n\n1. **Algodão egípcio 100%** — naturalmente hipoalergênico, sem tratamentos químicos agressivos\n2. **Fio a fio** — a textura suave reduz atrito com a pele\n3. **Linho** — respirável, antimicrobiano natural, ideal para peles reativas\n4. **Evite** misturas com poliéster — retêm calor e podem irritar\n\n**Argumento**: \"Para sua pele, eu recomendo o algodão egípcio fio a fio. É o que dermatologistas recomendam — puro, natural e tão suave que parece uma segunda pele.\"",
  "mesa": "**Mesa posta que impressiona — técnica Fassi**\n\n1. **Base**: toalha ou trilho em tom neutro (branco, cru ou cinza-perola)\n2. **Camadas**: sousplat em rattan ou madeira + prato principal Fassi\n3. **Altura**: copos e taças de alturas variadas criam ritmo visual\n4. **Toque final**: guardanapo de linho dobrado em formato simples, com um ramo de eucalipto\n\n**Regra de ouro**: a mesa posta não é para comer — é para **sonhar em receber**. Mostre ao cliente como a mesa Fassi transforma qualquer jantar em ocasião especial.\n\n**Fechamento**: \"Posso montar a mesa completa para você levar? Fica assim, pronta para impressionar seus convidados.\"",
  "casaCor": "**Coleção CasaCor vs. Inverno 2026**\n\n| Aspecto | CasaCor | Inverno 2026 |\n|---|---|---|\n| **Inspiração** | Arquitetura e design | Tardes de inverno brasileiras |\n| **Paleta** | Neutros sofisticados + dourado | Tons terrosos aquecidos |\n| **Foco** | Elegância atemporal | Aconchego e profundidade |\n| **Exclusividade** | Edição limitada do evento | Edição sazonal |\n| **Argumento** | \"A mesma coleção da CasaCor\" | \"Edição limitada de inverno\" |\n\n**Dica**: use a CasaCor como argumento de **autoridade** (\"a marca que veste a CasaCor\") e a Inverno como argumento de **urgência** (\"só este inverno\").",
};

export function getIaResposta(pergunta: string): string {
  const p = pergunta.toLowerCase();
  if (p.includes("percal") || p.includes("fio a fio")) return iaRespostas["percal"];
  if (p.includes("caro") || p.includes("preço") || p.includes("obje")) return iaRespostas["caro"];
  if (p.includes("inverno") || p.includes("2026")) return iaRespostas["inverno"];
  if (p.includes("pele") || p.includes("sensível") || p.includes("alergia")) return iaRespostas["pele"];
  if (p.includes("mesa") || p.includes("posta")) return iaRespostas["mesa"];
  if (p.includes("casacor") || p.includes("compare")) return iaRespostas["casaCor"];
  return "Sou a **Casa Marken Fassi IA**, sua especialista em enxovais premium. Posso ajudar com:\n\n• Diferenças entre tecidos e fios\n• Argumentos de venda para qualquer coleção\n• Técnicas de atendimento premium\n• Como lidar com objeções\n• Visual merchandising e arrumação\n• Informações sobre produtos Fassi\n\nO que você gostaria de saber?";
}
